feat: better handle inheritance
MovingBlocks/gestalt pull request #129
Opened 2021-11-14 18:39 UTC by pollend

- include super class properties to inject into
- don't instantiate interfaces/abstract classes

2021-11-15 07:04 UTC, DarkWeird requested changes
This PR breaking getting beans by interfaces and abstracts.
1. `CollectionResolveTest` is broken
2.  modified copy of `AbstractBeanTest#injectAbstractBean`:
```

    @Test
    public void injectAbstractBeanGetAbstract() {
        ServiceRegistry registry = new ServiceRegistry();
        registry.with(AbstractBeanTest.Impl1.class).lifetime(Lifetime.Singleton);
        registry.with(AbstractBeanTest.Impl2.class).lifetime(Lifetime.Singleton);
        registry.with(ConcreteImplementationFromAbs.class).lifetime(Lifetime.Singleton);

        BeanContext cntx = new DefaultBeanContext(registry);
        MyAbstractImplementation c1 = cntx.getBean(MyAbstractImplementation.class);

        Assert.assertNotNull(c1.impl);

    }
```
this modified test for getting as super class. don't works.

2021-11-15 07:04 UTC, DarkWeird commented on gestalt-inject-java/src/main/java/org/terasology/gestalt/annotation/processing/BeanDefinitionProcessor.java
> +            while (true) {
Don't use `while (true)` please.
I see how this works... but this line terrifies me.

2021-11-15 07:04 UTC, DarkWeird commented on gestalt-inject-java/src/main/java/org/terasology/gestalt/annotation/processing/BeanDefinitionProcessor.java
> +                return builder.add("return Optional.empty();").build();
How should works this line?
`MyAbstractImplementation` looks like usual non-abstract class..

2021-11-15 16:34 UTC, pollend commented on gestalt-inject-java/src/main/java/org/terasology/gestalt/annotation/processing/BeanDefinitionProcessor.java
> +                return builder.add("return Optional.empty();").build();
some classes can't be instantiated. I guess the logic is faulty. :/

2021-11-17 06:34 UTC, DarkWeird approved these changes

2021-11-17 06:35 UTC, merged