refactor(version): adjust to new semver 0.10.0 release
MovingBlocks/gestalt pull request #141
Opened 2024-01-14 23:15 UTC by jdrueckert

- after zafarkhaja went MIA after 2015, AntiLaby took over and released 0.10.0 in 2019
- zafarkhaja came back now and published a conflicting 0.10.0 release with breaking changes
  - getMajorVersion, getMinorVersion, getPatchVersion methods were removed
- fixed by using new majorVersion, minorVersion, patchVersion methods
- also switched to suggested alternatives for methods deprecated with 0.10.0
  - forIntegers -> of
  - valueOf -> parse
  - getPreReleaseVersion -> preReleaseVersion
  - increment[Major|Minor|Patch]Version -> next[Major|Minor|Patch]Version

2024-01-15 19:49 UTC, BenjaminAmos requested changes
This currently fails to compile with the error: `error: incompatible types: possible lossy conversion from long to int`.

Could you also update the `jsemver` dependency to the new `0.10.2` release to remove any ambiguity as to which artifact we depend on? There are still two differing resolvable `0.10.0` releases available to us.

2024-01-15 19:49 UTC, BenjaminAmos commented on gestalt-module/src/main/java/org/terasology/gestalt/naming/Version.java
> +        return semver.majorVersion();
```suggestion
        return (int) semver.majorVersion();
```

2024-01-15 19:49 UTC, BenjaminAmos commented on gestalt-module/src/main/java/org/terasology/gestalt/naming/Version.java
> +        return semver.minorVersion();
```suggestion
        return (int) semver.minorVersion();
```

2024-01-15 19:49 UTC, BenjaminAmos commented on gestalt-module/src/main/java/org/terasology/gestalt/naming/Version.java
> +        return semver.patchVersion();
```suggestion
        return (int) semver.patchVersion();
```

2024-01-16 23:02 UTC, BenjaminAmos approved these changes

2024-01-18 18:47 UTC, skaldarnar approved these changes

2024-01-18 18:48 UTC, merged